services: 
  green_code: 
    build:
      context: app
      target: runner
    ports: 
      - '8000:8000' 
    environment:
      - FLASK_APP=greenCode.py
      - FLASK_ENV=development
      - FLASK_RUN_PORT=8000
      - FLASK_RUN_HOST=0.0.0.0
      - gpt_ep=http://genaillm02.devnet.int:8081/v1/completions